### ISSUE TITLE
Theme Picker didn't follow System settings.

### ISSUE THREAD

**Issue by Dtrieb** [OMGSoundboard/android-app#67]
My smartphone is set to dark theme.
I started the app for the first time, and all is white.

Manually switch to dark, works.

## :iphone: Tech info
- Device: Pixel 7 pro
- OS: Android 14
- App Version: 11.0

**Comment by OMGSoundboard** [comment]
Thanks for the report, @Dtrieb. 👍
Do you have an idea about this, @Rashxz?

**Comment by Rashxz** [comment]
Ill take a look into it.

**Comment by dav23r** [comment]
I see this behavior reproducing for me.

More precisely:
*Follow system* -> light theme with dynamic colors.
*Dark* -> dark theme with app specific (bluish) color.
*Light* -> light theme with app specific  (bluish) color.

Device: Oneplus 5t (dumpling)
OS: Android 15 (Lineageos 22.2)
App version: 19.0 (fdroid)

**Comment by dav23r** [comment]
@Rashxz should we reopen this ticket? (I can create  a separate issue as well, but the title describes it already.)

edit: tagging @OMGSoundboard

**Comment by dav23r** [comment]
@OMGSoundboard
