### ISSUE TITLE
Edit Categories and Rename Sounds

### ISSUE THREAD

**Issue by BlueCobbleStone** [OMGSoundboard/android-app#70]
## :warning: Is your feature request related to a problem? Please describe
It's not possible to remove categories and rename sounds

## :bulb: Describe the solution you'd like
The possibility to remove default categories, add new ones, rename added sounds

## :raising_hand: Do you want to develop this feature yourself?

- [ ] Yes
- [X ] No

**Comment by OMGSoundboard** [comment]
That would be useful.
The implementation will take some time though.
Thanks for your feedback.

**Comment by OMGSoundboard** [comment]
Fixed with https://github.com/OMGSoundboard/android-app/pull/100.
