### ISSUE TITLE
Use the file's name as the tune's name/title by default

### ISSUE THREAD

**Issue by LaBetonneuse** [OMGSoundboard/android-app#83]
## :warning: Is your feature request related to a problem? Please describe
I'd like the tune's title to be the file's name by default, instead of having to type it myself, even though the file is properly named.

## :bulb: Describe the solution you'd like
When I select a file, the popup that asks me to type a title for the tune should be pre-filled with the file's name (without the extension)

## :bar_chart: Describe alternatives you've considered
Copy the file's name in the clipboard before importing it

## :page_facing_up: Additional context
N/A

## :raising_hand: Do you want to develop this feature yourself?
- [ ] Yes
- [X] No

**Comment by OMGSoundboard** [comment]
Are you interested to work on this, @Rashxz?

**Comment by Rashxz** [comment]
Sure!
