### ISSUE TITLE
Import several files (or a folder) at once

### ISSUE THREAD

**Issue by LaBetonneuse** [OMGSoundboard/android-app#84]
## :warning: Is your feature request related to a problem? Please describe
At the moment, only one file can be imported at a time.

## :bulb: Describe the solution you'd like
I'd like to be able to select several files at once (or even a whole folder) AND each file's name to be used as a title (see my other feature request : https://github.com/OMGSoundboard/android-app/issues/83).

## :bar_chart: Describe alternatives you've considered
Import each file individually. ☹️

## :page_facing_up: Additional context
N/A

## :raising_hand: Do you want to develop this feature yourself?
- [ ] Yes
- [x] No

**Comment by OMGSoundboard** [comment]
We will have a look at this. Thanks for your feedback.

**Comment by OMGSoundboard** [comment]
Fixed with https://github.com/OMGSoundboard/android-app/pull/100.
