### ISSUE TITLE
Delete Custom Sound

### ISSUE THREAD

**Issue by srouquette** [OMGSoundboard/android-app#91]
## :warning: Is your feature request related to a problem? Please describe

I don't see how I can customize the soundboard (even the material color). I'm not sure if I can remove custom sounds.

## :bulb: Describe the solution you'd like

Press and hold on a sound to make the menu appear (the one to set a ringtone), and add an entry to delete a sound from the app.

## :raising_hand: Do you want to develop this feature yourself?

- [ ] Yes
- [X] No

**Comment by OMGSoundboard** [comment]
Fixed with https://github.com/OMGSoundboard/android-app/pull/100.
